# Generated by Django 4.2.7 on 2023-12-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1992-01-01'),
            preserve_default=False,
        ),
    ]
